baseURL = "http://kuhungio.me"
languageCode = "zh-CN"
title = "Kuhung's Blog"
theme = "LeaveIt"
publishDir = "docs"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""

preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

[params]
    since = 2015
    author = "谷粒"                           # Author's name
    avatar = "/images/me/avatar.svg"           # Author's avatar
    subtitle = "Cut back the stems an inch to keep in bloom."         # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other

    google_verification = ""
   
    description = "不安分的数据挖掘/机器学习工程师" # site description
    keywords = "华中科技大学,谷洪,数据挖掘,网易游戏,用户分析,增长黑客,开发者,极客,代码,开源,Developer,Programmer,Coder,Geek,DataScientist" # site keywords

    beian = ""
    baiduAnalytics = ""

    license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

[params.social]
    GitHub = "kuhung"
    Wechat = "/images/me/wechat.jpg"  # Wechat QRcode image
    Email   = "kuhung@foxmail.com"

comment = true            # 是否开启评论
toc = true                # 是否开启目录
autoCollapseToc = true   # Auto expand and collapse toc

# Gitalk 评论配置（gitalk 请参考：https://github.com/gitalk/gitalk）
[params.gitalk] 
    owner = "kuhung"              # Your GitHub ID
    admin = "kuhung"      # GitHub repository owner and collaborators
    repo = "kuhung.github.io"               # The repo to store comments
    clientId = "7e5b8bd7063e5315e349"           # Your client ID
    clientSecret = "d6bd237e0a078b7e343775a47533d7b95d364899"       # Your client secret
    countSign = "条评论"

# disqus 评论配置
[params.disqus]
    name = "kuhungio"      # disqus_shortname
    lazy = true         # lazy to load disqus
